--- # dnf update
- hosts: all
  remote_user: am4
  become: yes
  gather_facts: no

  tasks:
  - name: dnf update cache
    dnf:
      update_cache: yes
  - name: dnf update
    dnf:
      name: "*"
      state: latest
